Added support for multi-line comments
mainak55512/stto pull request #6
Opened 2024-08-24 15:21 UTC by yogesh19k

I added a multiline comments map to the comments.go file and made the necessary changes to the countLine function in the utils.go file. I was unable to locate the multiline symbol for some languages, so I did not include them in the map. Please feel free to add any required languages.

2024-08-24 17:55 UTC, mainak55512 requested changes
Except one typo, the code is working fine and is ready to be merged.
Hi @yogesh19k, please fix the typo.

2024-08-24 17:55 UTC, mainak55512 commented on utils.go
> +			inside_multi_line_commentt=true
"inside_multi_line_commentt" variable is not defined. Please check @yogesh19k. There is a typo...

2024-08-24 18:18 UTC, yogesh19k commented
Fixed the typo, Please check

2024-08-25 07:40 UTC, mainak55512 approved these changes
All looks good

2024-08-25 07:49 UTC, merged